const logos = (prefix, sender) => {
  
// NÃO APAGUE ESSE ${prefix}, não coloque nada ${dentro assim} ISSO SÃO DEFINIÇÕES QUE ESTÁ PUXANDO DO settings.json, da pasta dono, só pode altera a base de tudo, menos as definições, só se quiser apagar a definição completa.  
  
  return `╭━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ💖❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╮
       ༺LOGOS༻
╰━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ💖❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╯

❯❯ LOGOS - VÍDEOS ❮❮

┠➥ [🩸] ${prefix}Pubgv (Texto)
┠➥ [🩸] ${prefix}Natalmsg (Texto)
┠➥ [🩸] ${prefix}Anonovo (Texto)
┠➥ [🩸] ${prefix}Trigrev (Texto)

❯❯ ATTP'S LOGOS ❮❮

┠➥ [🩸] ${prefix}attp1
┠➥ [🩸] ${prefix}attp2
┠➥ [🩸] ${prefix}attp3
┠➥ [🩸] ${prefix}attp4
┠➥ [🩸] ${prefix}attp5
┠➥ [🩸] ${prefix}attp6
┠➥ [🩸] ${prefix}attp7
┠➥ [🩸] ${prefix}gato
┠➥ [🩸] ${prefix}gerarnick

❯❯ LOGOS - 2 - TEXTOS ❮❮

┠➥ [🩸] ${prefix}Comporn (Texto/Texto)
┠➥ [🩸] ${prefix}Glitch (Texto/Texto)
┠➥ [🩸] ${prefix}Glitch3 (Texto/Texto)
┠➥ [🩸] ${prefix}Grafity (Texto/Texto)
┠➥ [🩸] ${prefix}Space (Texto/Texto)
┠➥ [🩸] ${prefix}Marvel (Texto/Texto)
┠➥ [🩸] ${prefix}GamePlay (Texto/Texto)
┠➥ [🩸] ${prefix}Stone (Texto/Texto)
┠➥ [🩸] ${prefix}Steel (Texto/Texto)
┠➥ [🩸] ${prefix}Ffbanner (Texto/Texto)
┠➥ [🩸] ${prefix}Avatar (Texto/Texto)
┠➥ [🩸] ${prefix}Videogame (Texto/Texto)
┠➥ [🩸] ${prefix}Pubg (Texto/Texto)
┠➥ [🩸] ${prefix}Thorstyle (Texto/Texto)

❯❯ LOGOS - 1 - TEXTO ❮❮

┠➥ [🩸] ${prefix}Neonlight (Texto)
┠➥ [🩸] ${prefix}plaq (Nome)
┠➥ [🩸] ${prefix}plaq2 (Nome)
┠➥ [🩸] ${prefix}plaq3 (Nome)
┠➥ [🩸] ${prefix}plaq4 (Nome)
┠➥ [🩸] ${prefix}Orangejuice (Texto)
┠➥ [🩸] ${prefix}Rainbowequalizer (Texto)
┠➥ [🩸] ${prefix}Peridot (Texto)
┠➥ [🩸] ${prefix}Rock (Texto)
┠➥ [🩸] ${prefix}Esmeralda (Texto)
┠➥ [🩸] ${prefix}3ddragon (Texto)
┠➥ [🩸] ${prefix}Purpleshiny (Texto)
┠➥ [🩸] ${prefix}Robotr2 (Texto)
┠➥ [🩸] ${prefix}Berry (Texto)
┠➥ [🩸] ${prefix}Hologram (Texto)
┠➥ [🩸] ${prefix}Cartoon (Texto)
┠➥ [🩸] ${prefix}Deepsea (Texto)
┠➥ [🩸] ${prefix}Shadow-sky (Texto)
┠➥ [🩸] ${prefix}Metallic (Texto)
┠➥ [🩸] ${prefix}Logoneon (Texto)
┠➥ [🩸] ${prefix}Ninjalogo (Texto)
┠➥ [🩸] ${prefix}Harry-potter (Texto)
┠➥ [🩸] ${prefix}Flower-typography (Texto)
┠➥ [🩸] ${prefix}Butterfly (Texto)
┠➥ [🩸] ${prefix}Starballons (Texto)
┠➥ [🩸] ${prefix}Frozen (Texto)
┠➥ [🩸] ${prefix}3dsilver (Texto)
┠➥ [🩸] ${prefix}Goldtext (Texto)
┠➥ [🩸] ${prefix}Illuminated-metallic (Texto)
┠➥ [🩸] ${prefix}Sweet-candy (Texto)
┠➥ [🩸] ${prefix}Strawberry (Texto)
┠➥ [🩸] ${prefix}Seta (Texto)
┠➥ [🩸] ${prefix}Grafite (Texto)
┠➥ [🩸] ${prefix}Goldt (Texto)
┠➥ [🩸] ${prefix}Tela (Texto)
┠➥ [🩸] ${prefix}3dboxtxt (Texto)
┠➥ [🩸] ${prefix}Chocolate-cake (Texto)
┠➥ [🩸] ${prefix}Magma (Texto)
┠➥ [🩸] ${prefix}Green-horror (Texto)
┠➥ [🩸] ${prefix}Blackpink2 (Texto)
┠➥ [🩸] ${prefix}Logobear (Texto)
┠➥ [🩸] ${prefix}Flaming (Texto)
┠➥ [🩸] ${prefix}Carved-wood (Texto)
┠➥ [🩸] ${prefix}Night-sky (Texto)
┠➥ [🩸] ${prefix}Naturalleaves (Texto)
┠➥ [🩸] ${prefix}Candycane (Texto)
┠➥ [🩸] ${prefix}Christmas (Texto)
┠➥ [🩸] ${prefix}Merrychristmas (Texto)
┠➥ [🩸] ${prefix}3ddeep (Texto)
┠➥ [🩸] ${prefix}Drug (Texto)
┠➥ [🩸] ${prefix}Americanflag (Texto)
┠➥ [🩸] ${prefix}Scifi (Texto)
┠➥ [🩸] ${prefix}Sandsummer (Texto)
┠➥ [🩸] ${prefix}Desfocado (Texto)
┠➥ [🩸] ${prefix}Vietnam (Texto)
┠➥ [🩸] ${prefix}Brilhante (Texto)
┠➥ [🩸] ${prefix}Sandwriting (Texto)
┠➥ [🩸] ${prefix}Sandengraved (Texto)
┠➥ [🩸] ${prefix}Summerysand (Texto)
┠➥ [🩸] ${prefix}Glue (Texto)
┠➥ [🩸] ${prefix}Dark (Texto)
┠➥ [🩸] ${prefix}Galaxystyle (Texto)
┠➥ [🩸] ${prefix}Minion (Texto)
┠➥ [🩸] ${prefix}Horrorgift (Texto)
┠➥ [🩸] ${prefix}Holographic (Texto)
┠➥ [🩸] ${prefix}Deluxe (Texto)
┠➥ [🩸] ${prefix}Glossyblue (Texto)
┠➥ [🩸] ${prefix}Deluxegold (Texto)
┠➥ [🩸] ${prefix}Glossycarbon (Texto)
┠➥ [🩸] ${prefix}Fabric (Texto)
┠➥ [🩸] ${prefix}Watercolor (Texto)
┠➥ [🩸] ${prefix}1917 (Texto)
┠➥ [🩸] ${prefix}Multicolor (Texto)
┠➥ [🩸] ${prefix}Generator (Texto)
┠➥ [🩸] ${prefix}Wonderful (Texto)
┠➥ [🩸] ${prefix}Holiday (Texto)
┠➥ [🩸] ${prefix}Technology (Texto)
┠➥ [🩸] ${prefix}Winter (Texto)
┠➥ [🩸] ${prefix}Neontext (Texto)
┠➥ [🩸] ${prefix}Halloweenfire (Texto)
┠➥ [🩸] ${prefix}Metaldark (Texto)
┠➥ [🩸] ${prefix}Darkgold (Texto)
┠➥ [🩸] ${prefix}Wicker (Texto)
┠➥ [🩸] ${prefix}Firework (Texto)
┠➥ [🩸] ${prefix}Steeltext (Texto)
┠➥ [🩸] ${prefix}Goldfoil (Texto)
┠➥ [🩸] ${prefix}Ultragloss (Texto)
┠➥ [🩸] ${prefix}Denimtext (Texto)
┠➥ [🩸] ${prefix}Stargreen (Texto)
┠➥ [🩸] ${prefix}Captain (Texto)
┠➥ [🩸] ${prefix}Toxic (Texto)
┠➥ [🩸] ${prefix}Ninjalogo (Texto)
┠➥ [🩸] ${prefix}Txtquadrinhos (Texto)
┠➥ [🩸] ${prefix}HackNeon (Texto)
┠➥ [🩸] ${prefix}EquipeMascote (Texto)
┠➥ [🩸] ${prefix}FFavatar (Texto)
┠➥ [🩸] ${prefix}Gizquadro (Texto)
┠➥ [🩸] ${prefix}Angelglx (Texto)
┠➥ [🩸] ${prefix}WingEffect (Texto)
┠➥ [🩸] ${prefix}Angelwing (Texto)
┠➥ [🩸] ${prefix}Blackpink (Texto)
┠➥ [🩸] ${prefix}Girlmascote (Texto)
┠➥ [🩸] ${prefix}Mascotegame (Texto)
┠➥ [🩸] ${prefix}Fpsmascote (Texto)
┠➥ [🩸] ${prefix}Logogame (Texto)
┠➥ [🩸] ${prefix}Glitch2 (Texto)
┠➥ [🩸] ${prefix}3DGold (Texto)
┠➥ [🩸] ${prefix}Placaloli (Texto)
┠➥ [🩸] ${prefix}Phadow (Texto)
┠➥ [🩸] ${prefix}Efeitoneon (Texto)
┠➥ [🩸] ${prefix}Cemiterio (Texto)
┠➥ [🩸] ${prefix}Metalgold (Texto)
┠➥ [🩸] ${prefix}Narutologo (Texto)
┠➥ [🩸] ${prefix}Narutologo2 (Texto)
┠➥ [🩸] ${prefix}Fire (Texto)
┠➥ [🩸] ${prefix}Romantic (Texto)
┠➥ [🩸] ${prefix}Smoke (Texto)
┠➥ [🩸] ${prefix}Papel (Texto)
┠➥ [🩸] ${prefix}Lovemsg (Texto)
┠➥ [🩸] ${prefix}Lovemsg2 (Texto)
┠➥ [🩸] ${prefix}Lovemsg3 (Texto)
┠➥ [🩸] ${prefix}Coffecup (Texto)
┠➥ [🩸] ${prefix}Coffecup2 (Texto)
┠➥ [🩸] ${prefix}Cup (Texto)
┠➥ [🩸] ${prefix}Florwooden (Texto)
┠➥ [🩸] ${prefix}Lobometal (Texto)
┠➥ [🩸] ${prefix}Harryp (Texto)
┠➥ [🩸] ${prefix}Txtborboleta (Texto)
┠➥ [🩸] ${prefix}Madeira (Texto)
┠➥ [🩸] ${prefix}Pornhub (Texto)
┠➥ [🩸] ${prefix}Escudo (Texto)
┠➥ [🩸] ${prefix}Transformer (Texto)
┠➥ [🩸] ${prefix}America (Texto)
┠➥ [🩸] ${prefix}Demongreen (Texto)
┠➥ [🩸] ${prefix}Wetglass (Texto) 
┠➥ [🩸] ${prefix}Toxic (Texto)
┠➥ [🩸] ${prefix}Neon3 (Texto)
┠➥ [🩸] ${prefix}Neondevil (Texto)
┠➥ [🩸] ${prefix}Neongreen (Texto)
┠➥ [🩸] ${prefix}Lava (Texto)
┠➥ [🩸] ${prefix}Halloween (Texto)
┠➥ [🩸] ${prefix}Neondevil (Texto)
┠➥ [🩸] ${prefix}DemonFire (Texto)
┠➥ [🩸] ${prefix}DemonGreen (Texto)
┠➥ [🩸] ${prefix}Thunderv2 (Texto)
┠➥ [🩸] ${prefix}Thunder (Texto)
┠➥ [🩸] ${prefix}Colaq (Texto)
┠➥ [🩸] ${prefix}Luxury (Texto)
┠➥ [🩸] ${prefix}Berry (Texto)
┠➥ [🩸] ${prefix}Transformer (Texto)
┠➥ [🩸] ${prefix}Matrix (Texto)
┠➥ [🩸] ${prefix}Horror (Texto)
┠➥ [🩸] ${prefix}Nuvem (Texto)
┠➥ [🩸] ${prefix}Neon (Texto)
┠➥ [🩸] ${prefix}Neon1 (Texto)
┠➥ [🩸] ${prefix}Neon2 (Texto)
┠➥ [🩸] ${prefix}Neon3d (Texto)
┠➥ [🩸] ${prefix}NeonGreen (Texto)
┠➥ [🩸] ${prefix}Neon3 (Texto)
┠➥ [🩸] ${prefix}Neve (Texto)
┠➥ [🩸] ${prefix}Areia (Texto)
┠➥ [🩸] ${prefix}Vidro (Texto)
┠➥ [🩸] ${prefix}Style (Texto)
┠➥ [🩸] ${prefix}Pink (Texto)
┠➥ [🩸] ${prefix}Carbon (Texto)
┠➥ [🩸] ${prefix}Metalblue (Texto)
┠➥ [🩸] ${prefix}Jeans (Texto)
┠➥ [🩸] ${prefix}Ossos (Texto)
┠➥ [🩸] ${prefix}Asfalto (Texto)
┠➥ [🩸] ${prefix}3dgoldenblack (Texto)
┠➥ [🩸] ${prefix}3d_business (Texto)
┠➥ [🩸] ${prefix}Summer (Texto)
┠➥ [🩸] ${prefix}Natal (Texto)
┠➥ [🩸] ${prefix}Jokerlogo (Texto)
┠➥ [🩸] ${prefix}Blood (Texto)
┠➥ [🩸] ${prefix}Break (Texto)
┠➥ [🩸] ${prefix}Fiction (Texto)
┠➥ [🩸] ${prefix}3dstone (Texto)
┠➥ [🩸] ${prefix}Lapis (Texto)
┠➥ [🩸] ${prefix}Gelo (Texto)
┠➥ [🩸] ${prefix}Rainbow (Texto)
┠➥ [🩸] ${prefix}Metalfire (Texto) 
┠➥ [🩸] ${prefix}Cria (Texto) 
┠➥ [🩸] ${prefix}Anime1 (Texto) 
┠➥ [🩸] ${prefix}Anime2 (Texto) 
┠➥ [🩸] ${prefix}Ff1 (Texto) 
┠➥ [🩸] ${prefix}Ff2 (Texto) 
┠➥ [🩸] ${prefix}Game (Texto) 
┠➥ [🩸] ${prefix}Entardecer (Texto) 
┠➥ [🩸] ${prefix}Indian (Texto) 
┠➥ [🩸] ${prefix}Ffrose (Texto) 
┠➥ [🩸] ${prefix}Ffgren (Texto) 
┠➥ [🩸] ${prefix}Chufuyu (Texto) 
┠➥ [🩸] ${prefix}Wolf (Texto) 
┠➥ [🩸] ${prefix}Dragonred (Texto) 
┠➥ [🩸] ${prefix}Purple (Texto) 
`;
};

exports.logos = logos;